version: 0.2

env:
  variables:
    REPO_NAME: "jvansan/modern-cicd-with-github-and-aws-codepipeline"
    IMAGE_TAG: "latest"  # Default value for the tag. Can be overridden.

phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - echo "Extracting AWS Account ID from CODEBUILD_BUILD_ARN..."
      - export ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - echo "Tagging the Docker image for ECR..."
      - docker tag $REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repository_name:$IMAGE_TAG
      - echo "Pushing the Docker image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repository_name:$IMAGE_TAG

  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"hotel-app","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repository_name:$IMAGE_TAG > imagedefinitions.json
      
artifacts:
  files: imagedefinitions.json